import {
  hotel1,
  hotel2,
  hotel3,
  hotel4,
  hotel5,
  hotel6,
  hotel7,
  hotel8,
  hotel9,
  hotel10,
  hotel11,
  hotel12,
  hotel13,
  hotel14,
  hotel15,
  hotel16,
  hotel17,
  hotel18,
  hotel19,
  hotel20,
  hotel21,
  hotel22,
  hotel23,
  hotel24,
  hotel25,
  hotel26,
  hotel27,
  hotel28,
  hotel29,
  hotel30,
  hotel31,
  hotel32,
  hotel33,
  hotel34,
  hotel35,
  hotel36,
  hotel37,
  hotel38,
  hotel39,
  hotel40,
  hotel41,
  hotel42,
  hotel43,
  hotel44,
  hotel45,
  hotel46,
  hotel47,
  hotel48
} from "./export";

const allImages = [
  //slide1
  { img: hotel1, title: "Toyota Camry", description: "Los Angeles, CA, USA" },
  { img: hotel2, title: "Ford Mustang", description: "Miami, FL, USA" },
  { img: hotel3, title: "Chevrolet Tahoe", description: "Houston, TX, USA" },
  { img: hotel4, title: "Honda Accord", description: "San Francisco, CA, USA" },
  { img: hotel5, title: "BMW X5", description: "New York, NY, USA" },
  { img: hotel6, title: "Audi A4", description: "Chicago, IL, USA" },
  // slide2
  { img: hotel7, title: "Toyota Corolla", description: "Tokyo, Japan" },
  { img: hotel8, title: "Jeep Wrangler", description: "New York, NY, USA" },
  { img: hotel9, title: "Volkswagen Golf", description: "Paris, France" },
  { img: hotel10, title: "Tesla Model S", description: "Rome, Italy" },
  { img: hotel11, title: "Mercedes-Benz C-Class", description: "London, UK" },
  { img: hotel12, title: "Lexus RX", description: "Dubai, UAE" },
  // slide3
  { img: hotel13, title: "Ford Focus", description: "Cairo, Egypt" },
  { img: hotel14, title: "Hyundai Elantra", description: "Barcelona, Spain" },
  { img: hotel15, title: "Kia Soul", description: "Rio de Janeiro, Brazil" },
  { img: hotel16, title: "Subaru Outback", description: "Venice, Italy" },
  { img: hotel17, title: "Nissan Altima", description: "Athens, Greece" },
  { img: hotel18, title: "Cadillac Escalade", description: "Moscow, Russia" },
  // slide4
  { img: hotel19, title: "Mazda CX-5", description: "Tanzania, Africa" },
  { img: hotel20, title: "Volvo XC90", description: "Berlin, Germany" },
  { img: hotel21, title: "Mini Cooper", description: "Cape Town, South Africa" },
  { img: hotel22, title: "Porsche 911", description: "San Francisco, CA, USA" },
  { img: hotel23, title: "Buick Enclave", description: "Amsterdam, Netherlands" },
  { img: hotel24, title: "Infiniti Q50", description: "Florence, Italy" },
  // slide5
  { img: hotel25, title: "Chrysler 300", description: "Edinburgh, Scotland" },
  { img: hotel26, title: "Land Rover Range Rover", description: "Vienna, Austria" },
  { img: hotel27, title: "Jaguar F-PACE", description: "Prague, Czech Republic" },
  { img: hotel28, title: "GMC Sierra", description: "Dublin, Ireland" },
  { img: hotel29, title: "Jeep Grand Cherokee", description: "Bangkok, Thailand" },
  { img: hotel30, title: "Subaru Forester", description: "Singapore" },
  // slide6
  { img: hotel31, title: "Volkswagen Tiguan", description: "Seoul, South Korea" },
  { img: hotel32, title: "Tesla Model 3", description: "Budapest, Hungary" },
  { img: hotel33, title: "Acura MDX", description: "Toronto, Canada" },
  { img: hotel34, title: "Mitsubishi Outlander", description: "Dubrovnik, Croatia" },
  { img: hotel35, title: "Lamborghini Huracan", description: "Kraków, Poland" },
  { img: hotel36, title: "Ferrari 488", description: "Havana, Cuba" },
  // slide7
  { img: hotel37, title: "Maserati Levante", description: "Mexico City, Mexico" },
  { img: hotel38, title: "Bentley Bentayga", description: "Hong Kong, China" },
  { img: hotel39, title: "Rolls-Royce Ghost", description: "Istanbul, Turkey" },
  { img: hotel40, title: "Porsche Cayenne", description: "Jerusalem, Israel" },
  { img: hotel41, title: "Aston Martin DB11", description: "Marrakech, Morocco" },
  { img: hotel42, title: "Ford Explorer", description: "Bangalore, India" },
  { img: hotel43, title: "Chevrolet Silverado", description: "Bangalore, India" },
  { img: hotel44, title: "GMC Yukon", description: "Bangalore, India" },
  { img: hotel45, title: "Subaru Crosstrek", description: "Bangalore, India" },
  { img: hotel46, title: "Toyota Highlander", description: "Bangalore, India" },
  { img: hotel47, title: "Jeep Renegade", description: "Bangalore, India" },
  { img: hotel48, title: "Nissan Rogue", description: "Bangalore, India" },
];

export default allImages;
