export { default as Complete } from './complete/Complete'
export { default as Home } from './home/Home'
export { default as Confirm } from './confirmation/Confirm'
export { default as Hotel } from './hotel/Hotel'
export { default as Login } from './login/Login'
export { default as Landing } from './landing/Landing'
export { default as Payment } from './payment/Payment'
export { default as Reserve } from './reservation/Reserve'
export { default as Signup } from'./signup/SignUp'
export { default as NotFound } from'./notfound/NotFound'